In [1]:
import os
os.chdir("..")

In [2]:
import pandas as pd
from src.utils.general import load_json

In [3]:
ROOT = "./models/text"

In [5]:
models = list(os.listdir(f"{ROOT}/node"))

raw_metrics = dict()

for model_setting in models:
    setting, model = model_setting.split("_")
    for dataset in os.listdir(f"{ROOT}/node/{model_setting}"):
        for split_type in os.listdir(f"{ROOT}/node/{model_setting}/{dataset}"):
            node_metrics = load_json(
                f"{ROOT}/node/{model_setting}/{dataset}/{split_type}/test_metrics.json"
            )
            edge_metrics = load_json(
                f"{ROOT}/edge/{model_setting}/{dataset}/{split_type}/test_metrics.json"
            )
            raw_metrics[(setting, model, dataset, split_type)] = {
                **{("Node", m): v for m, v in node_metrics.items()},
                **{("Edge", m): v for m, v in edge_metrics.items()},
            }
df = pd.DataFrame.from_dict(raw_metrics, orient="index")
df.index.names = ["setting", "model", "dataset", "split"]
df.columns.names = ["task", "metric"]

In [6]:
df

task                                         Node                      \
metric                                         f1 precision    recall
setting   model      dataset  split
shared    bge        dataset2 inductive  0.410955  0.412473  0.569679
                              hybrid     0.255127  0.277451  0.382772
                     dataset1 inductive  0.225326  0.253181  0.374558
                              hybrid     0.097901  0.102763  0.175392
          roberta    dataset2 inductive  0.345703  0.351199  0.602493
                              hybrid     0.268089  0.296092  0.422190
                     dataset1 inductive  0.176746  0.187120  0.307114
                              hybrid     0.076871  0.094488  0.119026
dedicated modernbert dataset2 inductive  0.123023  0.206322  0.218863
                              hybrid     0.178566  0.211518  0.299141
                     dataset1 inductive  0.068129  0.106122  0.111396
                              hybrid     0.053054  0.057890  0.094773
shared    modernbert dataset2 inductive  0.238938  0.322889  0.365117
                              hybrid     0.197844  0.228078  0.331462
                     dataset1 inductive  0.182666  0.218918  0.275075
                              hybrid     0.070702  0.087043  0.110046
dedicated roberta    dataset2 inductive  0.244386  0.283957  0.391655
                              hybrid     0.220794  0.248677  0.350992
                     dataset1 inductive  0.112529  0.148214  0.164697
                              hybrid     0.069572  0.074032  0.135373
          bert       dataset2 inductive  0.208359  0.243209  0.304287
                              hybrid     0.205161  0.254624  0.350645
                     dataset1 inductive  0.119029  0.152578  0.158943
                              hybrid     0.070865  0.079460  0.142520
shared    bert       dataset2 inductive  0.329187  0.315181  0.575303
                              hybrid     0.234913  0.262176  0.356474
                     dataset1 inductive  0.184956  0.191949  0.312875
                              hybrid     0.094261  0.102761  0.167455
dedicated bge        dataset2 inductive  0.217484  0.266647  0.248341
                              hybrid     0.219247  0.239128  0.375341
                     dataset1 inductive  0.101490  0.133218  0.187642
                              hybrid     0.068209  0.072906  0.143659

task                                         Edge
metric                                         f1 precision    recall
setting   model      dataset  split
shared    bge        dataset2 inductive  0.078573  0.096832  0.109369
                              hybrid     0.063872  0.085949  0.078119
                     dataset1 inductive  0.166743  0.191514  0.170412
                              hybrid     0.031933  0.032230  0.044808
          roberta    dataset2 inductive  0.084578  0.088000  0.117296
                              hybrid     0.092241  0.103972  0.117465
                     dataset1 inductive  0.154467  0.176802  0.154369
                              hybrid     0.031028  0.030886  0.045337
dedicated modernbert dataset2 inductive  0.000000  0.000000  0.000000
                              hybrid     0.009394  0.021213  0.010295
                     dataset1 inductive  0.022151  0.031847  0.020061
                              hybrid     0.006773  0.007744  0.008593
shared    modernbert dataset2 inductive  0.060982  0.081555  0.080398
                              hybrid     0.063475  0.076564  0.076001
                     dataset1 inductive  0.097168  0.119136  0.091649
                              hybrid     0.015960  0.017224  0.023313
dedicated roberta    dataset2 inductive  0.011008  0.018964  0.009144
                              hybrid     0.042414  0.048943  0.056107
                     dataset1 inductive  0.040285  0.058573  0.035424
                              hybrid     0.008609  0.009756  0.014791
          bert       dataset2 inductive  0.032228  0.038734  0.033028
                              hybrid     0.025151  0.031533  0.033228
                     dataset1 inductive  0.063864  0.081357  0.061628
                              hybrid     0.018045  0.019030  0.023731
shared    bert       dataset2 inductive  0.062544  0.079090  0.075610
                              hybrid     0.068784  0.084022  0.076684
                     dataset1 inductive  0.128538  0.151515  0.125967
                              hybrid     0.032075  0.032845  0.048415
dedicated bge        dataset2 inductive  0.019800  0.024861  0.022743
                              hybrid     0.019550  0.020264  0.024096
                     dataset1 inductive  0.052675  0.060526  0.051091
                              hybrid     0.014336  0.014820  0.021309

# DATASET 1

In [10]:
df.xs(("dataset1", "hybrid"), level=["dataset", "split"]).sort_index()

task                      Node                          Edge            \
metric                      f1 precision    recall        f1 precision
setting   model
dedicated bert        0.070865  0.079460  0.142520  0.018045  0.019030
          bge         0.068209  0.072906  0.143659  0.014336  0.014820
          modernbert  0.053054  0.057890  0.094773  0.006773  0.007744
          roberta     0.069572  0.074032  0.135373  0.008609  0.009756
shared    bert        0.094261  0.102761  0.167455  0.032075  0.032845
          bge         0.097901  0.102763  0.175392  0.031933  0.032230
          modernbert  0.070702  0.087043  0.110046  0.015960  0.017224
          roberta     0.076871  0.094488  0.119026  0.031028  0.030886

task
metric                  recall
setting   model
dedicated bert        0.023731
          bge         0.021309
          modernbert  0.008593
          roberta     0.014791
shared    bert        0.048415
          bge         0.044808
          modernbert  0.023313
          roberta     0.045337

In [11]:
df.xs(("dataset1", "inductive"), level=["dataset", "split"]).sort_index()

task                      Node                          Edge            \
metric                      f1 precision    recall        f1 precision
setting   model
dedicated bert        0.119029  0.152578  0.158943  0.063864  0.081357
          bge         0.101490  0.133218  0.187642  0.052675  0.060526
          modernbert  0.068129  0.106122  0.111396  0.022151  0.031847
          roberta     0.112529  0.148214  0.164697  0.040285  0.058573
shared    bert        0.184956  0.191949  0.312875  0.128538  0.151515
          bge         0.225326  0.253181  0.374558  0.166743  0.191514
          modernbert  0.182666  0.218918  0.275075  0.097168  0.119136
          roberta     0.176746  0.187120  0.307114  0.154467  0.176802

task
metric                  recall
setting   model
dedicated bert        0.061628
          bge         0.051091
          modernbert  0.020061
          roberta     0.035424
shared    bert        0.125967
          bge         0.170412
          modernbert  0.091649
          roberta     0.154369

# DATASET 2

In [12]:
df.xs(("dataset2", "hybrid"), level=["dataset", "split"]).sort_index()

task                      Node                          Edge            \
metric                      f1 precision    recall        f1 precision
setting   model
dedicated bert        0.205161  0.254624  0.350645  0.025151  0.031533
          bge         0.219247  0.239128  0.375341  0.019550  0.020264
          modernbert  0.178566  0.211518  0.299141  0.009394  0.021213
          roberta     0.220794  0.248677  0.350992  0.042414  0.048943
shared    bert        0.234913  0.262176  0.356474  0.068784  0.084022
          bge         0.255127  0.277451  0.382772  0.063872  0.085949
          modernbert  0.197844  0.228078  0.331462  0.063475  0.076564
          roberta     0.268089  0.296092  0.422190  0.092241  0.103972

task
metric                  recall
setting   model
dedicated bert        0.033228
          bge         0.024096
          modernbert  0.010295
          roberta     0.056107
shared    bert        0.076684
          bge         0.078119
          modernbert  0.076001
          roberta     0.117465

In [13]:
df.xs(("dataset2", "inductive"), level=["dataset", "split"]).sort_index()

task                      Node                          Edge            \
metric                      f1 precision    recall        f1 precision
setting   model
dedicated bert        0.208359  0.243209  0.304287  0.032228  0.038734
          bge         0.217484  0.266647  0.248341  0.019800  0.024861
          modernbert  0.123023  0.206322  0.218863  0.000000  0.000000
          roberta     0.244386  0.283957  0.391655  0.011008  0.018964
shared    bert        0.329187  0.315181  0.575303  0.062544  0.079090
          bge         0.410955  0.412473  0.569679  0.078573  0.096832
          modernbert  0.238938  0.322889  0.365117  0.060982  0.081555
          roberta     0.345703  0.351199  0.602493  0.084578  0.088000

task
metric                  recall
setting   model
dedicated bert        0.033028
          bge         0.022743
          modernbert  0.000000
          roberta     0.009144
shared    bert        0.075610
          bge         0.109369
          modernbert  0.080398
          roberta     0.117296