In [1]:
import os
os.chdir("..")

In [2]:
from src.utils import load_json
import pandas as pd

In [3]:
ROOT = "./models/text/test"

raw_res = dict()

for model_dir in os.listdir(ROOT):
    metrics = load_json(f"{ROOT}/{model_dir}/test_metrics.json")
    raw_res[model_dir] = metrics

results = pd.DataFrame(raw_res).T

In [4]:
results

                     f1  precision    recall
proj_256       0.035364   0.066450  0.057459
unfrozen_top4  0.026317   0.050463  0.045060
proj_128       0.037299   0.054557  0.061651
temp_0.05      0.071542   0.090003  0.116027
batch_1024     0.075616   0.090108  0.130007
temp_0.10      0.065900   0.070881  0.118535
temp_0.07      0.071166   0.089330  0.116325
batch_256      0.040513   0.057002  0.070706
temp_0.02      0.068828   0.080411  0.122192
unfrozen_top2  0.026317   0.050463  0.045060
proj_512       0.040927   0.065256  0.067018

In [5]:
results.sort_values("f1", ascending=False)

                     f1  precision    recall
batch_1024     0.075616   0.090108  0.130007
temp_0.05      0.071542   0.090003  0.116027
temp_0.07      0.071166   0.089330  0.116325
temp_0.02      0.068828   0.080411  0.122192
temp_0.10      0.065900   0.070881  0.118535
proj_512       0.040927   0.065256  0.067018
batch_256      0.040513   0.057002  0.070706
proj_128       0.037299   0.054557  0.061651
proj_256       0.035364   0.066450  0.057459
unfrozen_top4  0.026317   0.050463  0.045060
unfrozen_top2  0.026317   0.050463  0.045060